### ISSUE TITLE
Search Icon Design with Expandable Input 

### ISSUE THREAD

**Issue by JaseelaAlimahamed** [JaseelaAlimahamed/ServiceConnectUserUI#32]
Design a search icon component that transforms into a search input field when clicked. The input field should display a list of previous searches when expanded. Ensure the component is reusable for different parts of the application. Key requirements:

Initially display the search as an icon.
On click, the icon transitions into an expandable input field.
Show a dropdown list of previous search entries below the input field. we have to delete the search history items.
Ensure smooth  and responsive behavior.
Make the component modular and reusable across the application.

**Comment by jittocjoseph** [comment]
Completed
