### ISSUE TITLE
Request Service Page Design and Form Creation (Figma Page U18)

### ISSUE THREAD

**Issue by JaseelaAlimahamed** [JaseelaAlimahamed/ServiceConnectUserUI#37]
Create the request service page form based on the design specifications provided in Figma (Page U18). The page should not include a navbar and will navigate to the booking page upon clicking the confirm button. Key requirements:

Form Design:

Implement the form as per the layout and styling from Figma page U18.
Include all form fields and input types as specified (e.g., text fields, dropdowns, etc.).
Confirm Button Functionality:

After filling in the form, clicking the Confirm button should navigate the user to the booking page to finalize the request.
Exclusions:

No need to include a navbar on this page.
Responsive Layout:

Ensure the form is fully responsive across mobile and desktop views.

**Comment by voidx23** [comment]
Completed and Tested✅. Component working as required.
